# Generated by Django 4.2.16 on 2024-10-02 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
        ('accounts', '0002_delete_doctorprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='patient',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.patient'),
        ),
    ]
