# Generated by Django 4.2.16 on 2024-10-02 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_patientprofile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='patient',
        ),
    ]
