# Generated by Django 4.2.16 on 2024-10-07 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_patientprofile_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='name',
        ),
    ]
