# Generated by Django 4.2.16 on 2024-10-02 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_patientprofile_patient'),
        ('myapp', '0003_remove_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.patientprofile'),
        ),
    ]
