# Generated by Django 4.2.16 on 2024-10-02 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_patientprofile_patient'),
        ('myapp', '0004_patient_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.patientprofile'),
        ),
    ]
