# Generated by Django 4.2.16 on 2024-10-03 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_appointment_contact_number_appointment_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalhistory',
            old_name='treatment_history',
            new_name='treatment_plan',
        ),
    ]
