# Generated by Django 4.2.16 on 2024-10-04 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_patient_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalhistory',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.doctor'),
        ),
    ]
