# Generated by Django 4.2.16 on 2024-10-05 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_prescription_patient_prescription_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HealthEducationResource',
        ),
    ]
