# Generated by Django 4.2.16 on 2024-10-07 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_department_location_resources'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('policy_number', models.CharField(max_length=100)),
                ('coverage_details', models.TextField()),
            ],
        ),
    ]
